// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Neon serves a pooled ("-pooler") host that is not suitable for running
// migrations. Derive the direct (unpooled) URL automatically by stripping the
// "-pooler" segment so `prisma migrate` uses a direct connection while the
// running app keeps using the pooled connection via the pg adapter.
const pooled = process.env["DATABASE_URL"] ?? "";
const direct = process.env["DIRECT_URL"] ?? pooled.replace("-pooler", "");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: direct,
  },
});
